[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "channels>=4.3.2",
    "channels-redis>=4.3.0",
    "daphne>=4.2.3",
    "django>=6.1.1",
    "django-redis>=7.0.0",
    "djangorestframework>=3.18.1",
    "fakeredis>=2.39.0",
    "locust>=2.46.7",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.4",
    "redis>=8.1.0",
]
