# Generated by Django 6.1.1 on 2026-10-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_clan_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='games.clan'),
        ),
    ]
