# Generated by Django 6.1.1 on 2026-10-05 10:20

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_player_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_secret',
            field=models.CharField(default=games.models.generate_api_secret, max_length=64),
        ),
    ]
