# Generated by Django 6.1.1 on 2026-10-05 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=20)),
                ('period_identifier', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('percentile', models.FloatField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_leaderboards', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_ranks', to='games.player')),
            ],
            options={
                'ordering': ['period_identifier', 'rank'],
                'indexes': [models.Index(fields=['game', 'period_type', 'period_identifier', 'rank'], name='leaderboard_game_id_06f494_idx')],
                'unique_together': {('game', 'period_type', 'period_identifier', 'player')},
            },
        ),
    ]
